KailoTown_PlayersHouse_2F_Text_WantSleep::
    .string "The bed is very comfortable\p"
    .string "Do you want to go to sleep?$"

KailoTown_PlayersHouse_2F_Text_WentSleep::
    .string "{PLAYER} went to sleep.$"

KailoTown_PlayersHouse_2F_Text_Yawn::
    .string "Yawn...\p"
    .string "...\n"
    .string "...$"

KailoTown_PlayersHouse_2F_Text_TooEarly::
    .string "Nah, it's too early.$"

KailoTown_PlayersHouse_2F_Text_GBA::
    .string "It's a Gameboy!\p"
    .string "...\n"
    .string "...\p"
    .string "Batteries drained...$"

KailoTown_PlayersHouse_2F_Text_TV::
    .string "It's a TV.\p"
    .string "There's snow on the screen.$"

KailoTown_PlayersHouse_2F_Text_PlayNES::
    .string "It's a NES.\p"
    .string "Do you want to play?$"

KailoTown_PlayersHouse_2F_Text_NESOn::
    .string "{PLAYER} booted up the NES.$"

KailoTown_PlayersHouse_2F_Text_NoRival::
    .string "It's not the same without {RIVAL}...$"

KailoTown_PlayersHouse_2F_Text_Image::
    .string "It's a photo of\n"
    .string "MOON VALLEY...\p"
    .string "...\n"
    .string "...\p"
    .string "There's a gray pixel\n"
    .string "on the sky...$"
