KailoLabyard_Text_Vill::
		.string "Mirui...$"

KailoLabYard_Text_Victor_SelectMon::
		.string "Go ahead,\n"
		.string "they won't hurt you.$"

KailoLabYard_Text_Victor_TakeLetter::
		.string "Here.\n"
		.string "Take this letter and run to Ceru...$"

KailoLabYard_Text_Victor_Huh::
		.string "Huh?$"

KailoLabYard_Text_Victor_Something::
		.string "Something happened?$"

KailoLabYard_Text_StartBlackbirdMeeting_VictorLaugh::
		.string "???: Hahahahah!$"

KailoLabYard_Text_StartBlackbirdMeeting_VictorGilanGetOff::
		.string "???: GILAN!\n"
		.string "Stop licking my face!\p"
		.string "Please...\p"
		.string "...hahahah...\p"
		.string "...GILAN, enough...$"

KailoLabYard_Text_StartBlackbirdMeeting_VictorHello::
		.string "BLACKBIRD: Uch...\n"
		.string "Hello!$"

KailoLabYard_Text_StartBlackbirdMeeting_YoriHi::
		.string "???: {PLAYER}!$"

KailoLabYard_Text_StartBlackbirdMeeting_YoriLate::
		.string "{RIVAL}: Am I late?$"

KailoLabYard_Text_StartBlackbirdMeeting_VictorNotReally::
		.string "BLACKBIRD: Uh, no, not...\n"
		.string "Not really...\p"
		.string "You're the kids I'm supposed to\n"
		.string "send on a journey, right?$"

KailoLabYard_Text_StartBlackbirdMeeting_YoriYes::
		.string "{RIVAL}: Um, yes...\n"
		.string "Yes, professor!$"

KailoLabYard_Text_StartBlackbirdMeeting_VictorWell::
		.string "BLACKBIRD: Well...$"

KailoLabYard_Text_StartBlackbirdMeeting_VictorChoseOne::
		.string "BLACKBIRD: These EEVEE are\n"
		.string "triplets.\p"
		.string "Two brothers and a sister,\n"
		.string "all of them are one year old.\p"
		.string "Sigh... A few days after they\n"
		.string "hatched, your moms came to my lab\l"
		.string "to ask me to send you on a\l"
		.string "journey year later.\p"
		.string "Today...\p"
		.string "...as if they were hatched\n"
		.string "especially for you...\p"
		.string "Well...\n"
		.string "Pick one.\l"
		.string "And treat them well.$"

KailoLabYard_Text_StartBlackbirdMeeting_YoriLaugh1::
		.string "{RIVAL}: Haha...$"

KailoLabYard_Text_StartBlackbirdMeeting_YoriLaugh2::
		.string "Hahaha!$"

KailoLabYard_Text_StartBlackbirdMeeting_YoriCHoose::
		.string "I choose this one.\p"
		.string "BLACKBIRD: His name is GILAN.\p"
		.string "He is quite...\n"
		.string "Well...\p"
		.string "...crazy.\p"
		.string "I keep wondering where he gets so\n"
		.string "much energy from...$"

KailoLabYard_Text_StartBlackbirdMeeting_VictorAndYou::
		.string "And you?\p"
		.string "Come on, they won't\n"
		.string "bite you!$"

KailoLabYard_Text_StartBlackbirdMeeting_YoriWhere::
		.string "{RIVAL}: {PLAYER}!\n"
		.string "Where ae you going?\p"
		.string "You wanted a POKéMON so much\n"
		.string "now you'll just leave?$"

KailoLabYard_Text_StartBlackbirdMeeting_WantGilan::
		.string "{RIVAL}: Huh? Do you want\n"
		.string "GILAN, {PLAYER}?\p"
		.string "BLACKBIRD: No, you can't...\p"
		.string "{RIVAL}: It's okay, professor.\p"
		.string "{PLAYER} is my little cousin and\n"
		.string "I would do everything for him.$"

KailoLabYard_Text_StarBlackbirdMeeting_ChoseGilan::
		.string "BLACKBIRD: Well, then...\n"
		.string "Okay...$"

KailoLabYard_Text_StarBlackbirdMeeting_ReceivedMonFromYori::
		.string "{PLAYER} received the {STR_VAR_1}\n"
		.string "from {RIVAL}!$"

KailoLabYard_Text_StarBlackbirdMeeting_ReceivedStarter::
		.string "Well, now...$"

KailoLabYard_Text_StarBlackbirdMeeting_Balls::
		.string "These are...$"

KailoLabYard_Text_StarBlackbirdMeeting_DanSays::
		.string "{PLAYER}: POKé BALLS!\p"
		.string "I'm sorry...\p"
		.string "BLACKBIRD: No need\n"
		.string "to sorry, {PLAYER}.\p"
		.string "Yes, these are POKé BALLS...\p"
		.string "Do you know, what POKé BALLS\n"
		.string "are used for?$"

KailoLabYard_Text_StarBlackbirdMeeting_YoriBalls::
		.string "{RIVAL}: For catching wild POKéMON?$"

KailoLabYard_Text_StarBlackbirdMeeting_VictorYesBalls::
		.string "BLACKBIRD: Yes. They are used for\n"
		.string "catching wild POKéMON.\p"
		.string "Do you know how to catch\n"
		.string "a POKéMON?$"

KailoLabYard_Text_StarBlackbirdMeeting_VictorShow::
		.string "I'll show you.$"

KailoLabYard_Text_StartBlackbirdMeeting_VillReady::
		.string "VILL, can I...?$"
	
KailoLabYard_Text_StartBlackbirdMeeting_Whew::
		.string "BLACKBIRD: ...\n"
		.string "Whew...\p"
		.string "Well...\n"
		.string "Come back, buddy!$"

KailoLabYard_Text_StartBlackbirdMeeting_LetMe::
		.string "Let me just...$"

KailoLabYard_Text_StartBlackbirdMeeting_BrokeBall::
		.string "PROF. BLACKBIRD broke the\n"
		.string "POKé BALL!$"

KailoLabYard_Text_StartBlackbirdMeeting_ThatsIt::
		.string "Well...\n"
		.string "That's it!\p"
		.string "Try it now by yourself.\p"
		.string "{RIVAL}: Okay...$"

KailoLabYard_Text_StartBlackbirdMeeting_Nyiagh::
		.string "Nyiagh!$"

KailoLabYard_Text_StartBlackbirdMeeting_YoriUsedBall::
		.string "{RIVAL} used the\n"
		.string "POKé BALL!$"

KailoLabYard_Text_StartBlackbirdMeeting_YoriCaught::
		.string "Gotcha!\n"
		.string "{RIVAL} caught {STR_VAR_1}!$"


KailoLabYard_Text_StartBlackbirdMeeting_YoriIDidIt::
		.string "{RIVAL}: I...\p"
		.string "I did it...?\p"
		.string "BLACKBIRD: Yes, you did.\p"
		.string "{RIVAL}: Hahah! Yes!\n"
		.string "{PLAYER}, have you seen that?\p"
		.string "I caught {STR_VAR_1}!$"

KailoLabYard_Text_AfterTutorial_YourTurn::
		.string "BLACKBIRD: So, {PLAYER}.\p"
		.string "I think it's your turn now.$"

KailoLabYard_Text_AfterTutorial_PlayerUsedBall::
		.string "{PLAYER} used the\n"
		.string "POKé BALL!$"

KailoLabYard_Text_StartBlackbirdMeeting_PlayerCaught::
		.string "Gotcha!\n"
		.string "{STR_VAR_1} was caught!$"

KailoLabYard_Text_Victor_NoBattle::
        .string "BLACKBIRD: No!$"

KailoLabYard_Text_Victor_NoBattle2::
        .string "Please...\p"
        .string "They're siblings, I don't want\n"
        .string "to watch them getting hurt.$"

KailoLabYard_Text_Yori_NoBattle::
        .string "{RIVAL}: Okay, professor...$"

KailoLabYard_Text_Yori_GoHome::
        .string "Let's go home, {PLAYER}...$"

KailoLabYard_Text_YoriVill::
        .string "{RIVAL}: {PLAYER}...\n"
        .string "What do you think?\l"
        .string "What's that blue POKéMON?\p"
        .string "...\p"
        .string "...yeah...\n"
        .string "I don't know either...$"
