gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string "PINK$"

gNameChoice_Red::
    .string "TURQUOISE$"

gNameChoice_Leaf::
    .string "MIND$"

gNameChoice_Fire::
    .string "COLD$"

gNameChoice_Gary::
    .string "YORI$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "DAN$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "VICTOR$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "MAT$"

gNameChoice_Kamon::
    .string "PAT$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "DAMIEN$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JIM$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OWL$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "HELEN$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "VENTI$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "MIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gControlsGuide_Text_AButton::
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gControlsGuide_Text_BButton::
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gControlsGuide_Text_StartButton::
    .string "Press this button to open the\n"
    .string "MENU.$"

gControlsGuide_Text_SelectButton::
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gControlsGuide_Text_LRButtons::
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gPikachuIntro_Text_Page1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gPikachuIntro_Text_Page2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gPikachuIntro_Text_Page3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "This is game is based on the\n"
    .string "POKéMON EEVEE ADVENTURES story,\n"
    .string "written by GEEVEE LA FORGE.\p$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Hello, there!\n"
    .string "I was expecting you!\p"
    .string "Welcome to the world of POKéMON!\p"
    .string "My name is BLACKBIRD.\p"
    .string "People sometimes refer to me as\n"
    .string "PROFESSOR BLACKBIRD\p$"

gOakSpeech_Text_ThisWorld::
    .string "This world…\p"
    .string "...\n"
    .string "...\p$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "VILL! Not now, please!\p"
    .string "...\n"
    .string "...\p"
    .string "What was I talking about?\p" 
    .string "Oh! The world is inhabited\n" 
    .string "far and wide by animals\p"
    .string "called POKéMON.\p" 
    .string "I'm sorry, this is my first time,\n"
    .string "I'm a little stressed.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\p"
    .string "As for myself…\p"
    .string "I observe the POKéMON and learn\n"
    .string "from them as much as I can.\p"
    .string "This is my work and passion.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "But first, tell me a something\n"
    .string "about yourself.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Let's begin with your name.\n"
    .string "What is it?$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Okay...\n"
    .string "So your name is {PLAYER}.\p" 
    .string "Am I right?$"

gOakSpeech_Text_WhatWasHisName::
    .string "This is your cousin.\p"
    .string "You've always supported\n"
    .string "each other since you\p"
    .string "were babies.\n"
    .string "…can you remind me his name?\p$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Your rival's name, what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "So, it is {RIVAL}, right?$"

gOakSpeech_Text_RememberRivalsName::
    .string "Thank you.\p$"

gOakSpeech_Text_LetsGo::
    .string "So, {PLAYER}.\p"
    .string "Your very own POKéMON\n"
    .string "adventure is about to unfold!\p"
    .string "A world of dreams and adventures\n"
    .string "with POKéMON awaits!\p"
    .string "Come, meet me in my Lab.\n"
    .string "I've got something for you both.\p$"
