Text_FirstShouldRestoreMonsHealth::
	.string "First, you should restore your\n"
	.string "POKéMON to full health.$"

Text_MonsHealedShouldBuyPotions::
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "If your POKéMON's energy, HP,\n"
	.string "is down, please come see us.\p"
	.string "If you're planning to go far in the\n"
	.string "field, you should buy some POTIONS\l"
	.string "at the POKéMON MART.\p"
	.string "We hope you excel!$"

Text_MonsHealed::
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "We hope you excel!$"

Text_YawnAfterFaint::
    .string "Yawn...\n"
    .string ".......$"

Text_HadQuiteAnExperienceTakeRest::
	.string "The POKéMON is holding\n"
	.string "a MAIL.\p"
	.string "“{PLAYER},\p"
	.string "I couldn't wait for you to wake up,\n"
	.string "I had a lot of work at the VALLEY,\l"
	.string "so I sent VILL to take care of you.\p"
    .string "You had a quite rough battle,\n"
    .string "I hope you had a good rest.\p"
    .string "I took your POKéMON and left them\n"
    .string "healed on your shelf, so they're\l"
    .string "ready for your next adventure.\p"
    .string "Remember to keep some POTIONS\n"
    .string "in your pack.\p"
    .string "you can buy them from DIRK,\n"
    .string "the shopkeeper at POKéMON CENTER.\p"
    .string "\n"
    .string "Take care of my EEVEE,\l"
    .string "PROF. BLACKBIRD“$"

FaintedHouse_Got_Mon::
	.string "{PLAYER} obtained\n"
	.string "POKéMON!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} panicked and lost ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_WhitedOut::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} whited out!$"
