KailoTown_Text_JennyStopWait::
    .string "???: Hey!\n"
    .string "What are you doing there?!$"

KailoTown_Text_JennyStopUnsafe::
    .string "It's unsafe there!\p"
    .string "Wild POKéMON live in tall grass\n"
    .string "and inside the tunnel.\p"
    .string "You need your a POKéMON for\n"
    .string "your own protection.\p"
    .string "Get back here!$"

KailoTown_Text_JennyStopNoPassing::
    .string "I won't let you pass without\n"
    .string "POKéMON.$"

KailoTown_Text_LabSign::
    .string "LAIGEN and BLACKBIRD\n"
    .string "RESEARCH LAB$"

KailoTown_Text_DC::
    .string "DELICIOUS CAFé\n"
    .string "RESTAURANT$"

KailoTown_Text_KailoSign::
    .string "KAILO TOWN\n"
    .string "A quiet paradise on earth.$"

KailoTown_Text_Mailbox::
    .string "{PLAYER}'s and {RIVAL}'s house$"

KailoTown_Text_HelenMailbox::
    .string "HELEN BLACKBIRD's house$"

KailoTown_Text_DoorClosed::
    .string "The door are closed...$"

KailoTown_Text_UnderConstruction::
    .string "KAILO TOWN POKéMON GYM\n"
    .string "Under Construction$"

KailoTown_Text_Gym::
    .string "KAILO TOWN POKéMON GYM\n"
    .string "(TEMPORARY) LEADER:\l"
    .string "VICTOR$"

KailoTown_Text_Unloader::
    .string "...POTIONs, BALLs... Hmm...\n"
    .string "There's so many ANTIDOTEs...\p"
    .string "...\n"
    .string "...$"

KailoTown_Text_GetOff::
    .string "Hey!\n"
    .string "Don't hang around here, kid!$"

KailoTown_Text_NoPopular::
    .string "KAILO isn't\n"
    .string "very popular.\p"
    .string "It's not even at the\n"
    .string "TOWN MAP!$"

KailoTown_Text_NoLeader::
    .string "Sorry, kid!\p"
    .string "The Gym is not finished yet.\p"
    .string "But even if it was,\n"
    .string "we don't have a Leader.\p"
    .string "...\n"
    .string "...\p"
    .string "Blaine?\p"
    .string "I heard that became part\n"
    .string "of the Elite Four...\p"
    .string "...And there's too many trees\n"
    .string "for Fire Pokémon Leader...$"

KailoTown_Text_NoNurse::
	.string "Hey, kid!\n"
	.string "You're looking for a DOCTOR?\p"
	.string "She went to the MOON VALLEY this\n"
	.string "night and didn't came back yet.\l"
	.string "You'll have to wait for her.$"
