KailoTown_Text_JennyStopWait::
    .string "???: Hey!\n"
    .string "What are you doing there?!$"

KailoTown_Text_JennyStopUnsafe::
    .string "It's unsafe there!\p"
    .string "Wild POKéMON live in tall grass\n"
    .string "and inside the tunnel.\p"
    .string "You need your own POKéMON for\n"
    .string "your own protection.\p"
    .string "Get back here!$"

KailoTown_Text_JennyStopNoPassing::
    .string "I won't let you pass without\n"
    .string "POKéMON.$"

